name: spack macOS Python

on:
  push:
  pull_request:

# GitHub Action Limits
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

jobs:
  install_qt_clang:
    name: install qt
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: spack install
      run: |
        . install_spack.sh
        spack install -v py-qtconsole %clang

